//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopatkin_Glazki
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int AgentTypeID { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public string DirectorName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Logo { get; set; }
        public int Priority { get; set; }
    
        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ProductSale ProductCount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
        public string AgentTypeString
        {
           get
           {
                return AgentType.Title;
           }
        }
        public virtual ICollection<ProductSale> ProductSales { get; set; }
        /*  public int NumberOfsales
          {
              get
              {
                  int coint = 0;
                  var ProductSale = Lopatkin_GlazkiEntities.GetContext().ProductSale.ToList();
                  foreach(var el in ProductSale)
                  {
                      if (this.ID == el.AgentID)
                      {
                          coint += el.ProductCount;
                      }
                  }
                  return coint;
              }
          }*/
        public decimal Discount
        {
            get
            {
                int count=0;
                decimal res = 0;
                var discount =Lopatkin_GlazkiEntities.GetContext().Product.ToList();
                foreach(var el in ProductSale)
                {
                    if (el.AgentID == ID)
                    {
                        foreach(var el1 in discount)
                        {
                            if (el1.ID == ID)
                            {
                                res += el1.MinCostForAgent * el.ProductCount;
                            }
                        }
                    }
                }
                if (res < 10000)
                {
                    count = 0;
                }
                if (res >= 10000&&res<=50000)
                {
                    count = 5;
                }
                if (res >= 50000 && res <= 150000)
                {
                    count = 10;
                }
                if (res >= 150000 && res <= 500000)
                {
                    count = 20;
                }
                if (res >500000)
                {
                    count = 25;
                }
                return count;
            }
        }
    }
}
