//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopatkin_Glazki
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATS_LopatkinEntities4 : DbContext
    {
        private static ATS_LopatkinEntities4 _context;
        public static ATS_LopatkinEntities4 GetContext()
        {
            if (_context == null)
            {
                _context = new ATS_LopatkinEntities4();

            }
            return _context;
        }
        public ATS_LopatkinEntities4()
            : base("name=ATS_LopatkinEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATS> ATS { get; set; }
        public virtual DbSet<Абоненты> Абоненты { get; set; }
        public virtual DbSet<Ведомость_абонентской_платы> Ведомость_абонентской_платы { get; set; }
        public virtual DbSet<Ведомость_звонков> Ведомость_звонков { get; set; }
        public virtual DbSet<Прайс_АТС> Прайс_АТС { get; set; }
    }
}
