//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopatkin_Glazki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Абоненты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Абоненты()
        {
            this.Ведомость_абонентской_платы = new HashSet<Ведомость_абонентской_платы>();
            this.Ведомость_звонков = new HashSet<Ведомость_звонков>();
        }
    
        public int ID_абонента { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Вид_телефона { get; set; }
        public string Номер_телефона { get; set; }
        public string Межгород { get; set; }
        public string Льгота { get; set; }
        public string Индекс_дома { get; set; }
        public string Район { get; set; }
        public string Улица { get; set; }
        public string Дом { get; set; }
        public string Квартира { get; set; }
        public int ID_ATS { get; set; }
        public string Logo { get; set; }
        public Nullable<System.DateTime> End_contract { get; set; }
    
        public virtual ATS ATS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ведомость_абонентской_платы> Ведомость_абонентской_платы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ведомость_звонков> Ведомость_звонков { get; set; }
    }
}
