//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopatkin_Glazki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ведомость_абонентской_платы
    {
        public int ID_платы { get; set; }
        public int ID_абонента { get; set; }
        public string Месяц { get; set; }
        public int Год { get; set; }
        public Nullable<int> Количество_минут_на_городские { get; set; }
        public Nullable<int> Количество_минут_на_межгород { get; set; }
        public decimal Стоимость { get; set; }
        public Nullable<decimal> Сумма_льготы { get; set; }
        public Nullable<decimal> Общая_стоимость { get; set; }
    
        public virtual Абоненты Абоненты { get; set; }
    }
}
