//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopatkin_Glazki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ведомость_звонков
    {
        public int ID_звонка { get; set; }
        public int ID_абонента { get; set; }
        public System.DateTime Дата_звонка { get; set; }
        public System.TimeSpan Время_начала { get; set; }
        public System.TimeSpan Время_окончания { get; set; }
        public string Межгород { get; set; }
    
        public virtual Абоненты Абоненты { get; set; }
    }
}
