//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lopatkin_Glazki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Прайс_АТС
    {
        public int ID_прайса { get; set; }
        public int ID_ATS { get; set; }
        public decimal Цена_на_городские { get; set; }
        public decimal Цена_на_межгород { get; set; }
    
        public virtual ATS ATS { get; set; }
    }
}
